version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: allaboutme-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: allaboutme
    ports:
      - "5433:5432"  # Changed to 5433 to avoid conflict
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: allaboutme-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

