[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.watchPatterns]
include = ["backend/**", "frontend/**", "Dockerfile", "start.sh", "railway.json"]

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
sleepApplication = false

# Region (optional - Railway auto-selects best)
# region = "us-west1"

# Custom domains (add after deployment)
# [deploy.domains]
# production = "app.yourdomain.com"

