"""Add automation tables

Revision ID: 0937ce8d5a1c
Revises: 42b6a8d8d730
Create Date: 2025-10-14 00:53:16.885295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0937ce8d5a1c'
down_revision = '42b6a8d8d730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

