"""Add automation tables

Revision ID: 42b6a8d8d730
Revises: 5df841f70605
Create Date: 2025-10-14 00:52:53.204492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b6a8d8d730'
down_revision = '5df841f70605'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

